# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8888, host: 8888
  config.vm.define "ayagmur" do |node|
	node.vm.hostname = "ayagmur"
	node.vm.network "private_network", ip: "192.168.56.110"
	node.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    node.vm.provider "virtualbox" do |vb|
		vb.name = "ayagmur"
        vb.memory = 4024
        vb.cpus = 2
	end
	node.vm.provision "shell", path: "../scripts/run.sh"
  end
  
end
