# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/focal64"

  config.vm.define "ayagmurS" do |node|
	node.vm.hostname = "ayagmurS"
	node.vm.network "private_network", ip: "192.168.56.110"
    node.vm.provider "virtualbox" do |vb|
		vb.name = "ayagmurS"
        vb.memory = 512
        vb.cpus = 1
	  end
	node.vm.provision "shell", path: "./scripts/controller.sh"
  end


  config.vm.define "ayagmurSW" do |node|
	node.vm.hostname = "ayagmurSW"
	node.vm.network "private_network", ip: "192.168.56.111"
    node.vm.provider "virtualbox" do |vb|
		vb.name = "ayagmurSW"
        vb.memory = 512
        vb.cpus = 1
    end
	node.vm.provision "shell", path: "./scripts/agent.sh", args: ["192.168.56.110"]
  end
  
end
